### ISSUE TITLE
have you tested your model on real data?

### ISSUE THREAD

**Issue by liwenssss** [AlextheEngineer/Ego3DHand#2]
Hi, I use your data to train a simple model.But I found it worked worse on the real image data.Have you tested your model on the real image data?Can you give any advice?

**Comment by AlextheEngineer** [comment]
Thanks for asking! Generally, there is a domain gap between synthetic and real data. The differences between low-level features make it hard for CNNs to recognize. If you need to test on real images, you could try experimenting with FreiHand, CMU Panoptic or other datasets with real hand images. Note that annotations for real hand images are much more challenging, therefore such data is more limited in variety and quantity. Also, domain gap might still exist due to variables like pose space, lighting, view angle, etc. We are currently annotating a new dataset with egocentric two-hand real images and it will be ready later this year. Let me know if you have more questions!

________________________________

**Comment by liwenssss** [comment]
Nice work and I really look forward to it!



发自我的iPhone


------------------ Original ------------------
